apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-deployment
  labels:
    run: timesheet
spec:
  replicas: 1
  selector:
    matchLabels:
      run: timesheet
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: timesheet
      name: timesheet
    spec:
      containers:
        - image: hajedkhlifi/timesheet
          env:
            - name: DB_USER
              value: root
            - name: DB_PWD
              value: "1234"
            - name: DB_HOST
              value: mysql
          imagePullPolicy: IfNotPresent
          name: timesheet
          ports:
            - containerPort: 8082
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: timesheet
  name: timesheet
spec:
  ports:
    - port: 8082
      nodePort: 31080
      protocol: TCP
      targetPort: 8082
  selector:
    run: timesheet
  type: NodePort
status:
  loadBalancer: {}